<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Beatmaps\**\*" />
    <EmbeddedResource Include="Fonts\**\*" />
    <EmbeddedResource Include="Samples\**\*" />
    <EmbeddedResource Include="Skins\**\*" />
    <EmbeddedResource Include="Shaders\**\*" />
    <EmbeddedResource Include="Textures\**\*" />
    <EmbeddedResource Include="Tracks\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\osu.Game.Plugins\osu.Game.Plugins.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ppy.osu.Game" Version="2025.1209.0" />
  </ItemGroup>

</Project>
