using osu.Framework.Extensions;
using osu.Game.Users;

namespace osu.Plugin.LegacyExperience.Online;

partial class LegacyUserPanel
{
    private readonly record struct CountryInfo(int TimezoneOffset, string DisplayName);

    private static CountryInfo GetCountryInfo(CountryCode countryCode)
    {
        var displayName = countryCode.GetDescription();

        // Lazer's server doesn't provide timezone info, so we hard code a mapping here.
        // Note that unlike stable, countryCode is not a realtime value,
        // the timezoneOffset doesn't reflect the actual timezone of the user.
        // For example, a Chinese user uses VPN to connect to osu! servers in the JP,
        // we get CountryCode.CN and his timezone is still UTC+8 instead of UTC+9.
        int timezoneOffset = countryCode switch
        {
            CountryCode.A1 => 0, // Anonymous Proxy
            CountryCode.A2 => 0, // Satellite Provider
            CountryCode.AD => 60, // UTC+1
            CountryCode.AE => 240, // UTC+4
            CountryCode.AF => 270, // UTC+4:30
            CountryCode.AG => -240, // UTC-4
            CountryCode.AI => -240, // UTC-4
            CountryCode.AL => 60, // UTC+1
            CountryCode.AM => 240, // UTC+4
            CountryCode.AN => -240, // UTC-4
            CountryCode.AO => 60, // UTC+1
            CountryCode.AP => 0, // Asia/Pacific (varies)
            CountryCode.AQ => 0, // Antarctica (varies)
            CountryCode.AR => -180, // UTC-3
            CountryCode.AS => -660, // UTC-11
            CountryCode.AT => 60, // UTC+1
            CountryCode.AU => 600, // UTC+10 (varies)
            CountryCode.AW => -240, // UTC-4
            CountryCode.AX => 120, // UTC+2
            CountryCode.AZ => 240, // UTC+4
            CountryCode.BA => 60, // UTC+1
            CountryCode.BB => -240, // UTC-4
            CountryCode.BD => 360, // UTC+6
            CountryCode.BE => 60, // UTC+1
            CountryCode.BF => 0, // UTC+0
            CountryCode.BG => 120, // UTC+2
            CountryCode.BH => 180, // UTC+3
            CountryCode.BI => 180, // UTC+3
            CountryCode.BJ => 60, // UTC+1
            CountryCode.BL => -240, // UTC-4
            CountryCode.BM => -240, // UTC-4
            CountryCode.BN => 480, // UTC+8
            CountryCode.BO => -240, // UTC-4
            CountryCode.BQ => -240, // UTC-4
            CountryCode.BR => -180, // UTC-3 (varies)
            CountryCode.BS => -300, // UTC-5
            CountryCode.BT => 360, // UTC+6
            CountryCode.BV => 0, // UTC+0
            CountryCode.BW => 120, // UTC+2
            CountryCode.BY => 180, // UTC+3
            CountryCode.BZ => -360, // UTC-6
            CountryCode.CA => -300, // UTC-5 (varies)
            CountryCode.CC => 390, // UTC+6:30
            CountryCode.CD => 60, // UTC+1
            CountryCode.CF => 60, // UTC+1
            CountryCode.CG => 60, // UTC+1
            CountryCode.CH => 60, // UTC+1
            CountryCode.CI => 0, // UTC+0
            CountryCode.CK => -600, // UTC-10
            CountryCode.CL => -180, // UTC-3
            CountryCode.CM => 60, // UTC+1
            CountryCode.CN => 480, // UTC+8
            CountryCode.CO => -300, // UTC-5
            CountryCode.CR => -360, // UTC-6
            CountryCode.CU => -300, // UTC-5
            CountryCode.CV => -60, // UTC-1
            CountryCode.CW => -240, // UTC-4
            CountryCode.CX => 420, // UTC+7
            CountryCode.CY => 120, // UTC+2
            CountryCode.CZ => 60, // UTC+1
            CountryCode.DE => 60, // UTC+1
            CountryCode.DJ => 180, // UTC+3
            CountryCode.DK => 60, // UTC+1
            CountryCode.DM => -240, // UTC-4
            CountryCode.DO => -240, // UTC-4
            CountryCode.DZ => 60, // UTC+1
            CountryCode.EC => -300, // UTC-5
            CountryCode.EE => 120, // UTC+2
            CountryCode.EG => 120, // UTC+2
            CountryCode.EH => 0, // UTC+0
            CountryCode.ER => 180, // UTC+3
            CountryCode.ES => 60, // UTC+1
            CountryCode.ET => 180, // UTC+3
            CountryCode.EU => 60, // UTC+1 (varies)
            CountryCode.FI => 120, // UTC+2
            CountryCode.FJ => 720, // UTC+12
            CountryCode.FK => -180, // UTC-3
            CountryCode.FM => 600, // UTC+10
            CountryCode.FO => 0, // UTC+0
            CountryCode.FR => 60, // UTC+1
            CountryCode.FX => 60, // UTC+1
            CountryCode.GA => 60, // UTC+1
            CountryCode.GB => 0, // UTC+0
            CountryCode.GD => -240, // UTC-4
            CountryCode.GE => 240, // UTC+4
            CountryCode.GF => -180, // UTC-3
            CountryCode.GG => 0, // UTC+0
            CountryCode.GH => 0, // UTC+0
            CountryCode.GI => 60, // UTC+1
            CountryCode.GL => -180, // UTC-3
            CountryCode.GM => 0, // UTC+0
            CountryCode.GN => 0, // UTC+0
            CountryCode.GP => -240, // UTC-4
            CountryCode.GQ => 60, // UTC+1
            CountryCode.GR => 120, // UTC+2
            CountryCode.GS => -120, // UTC-2
            CountryCode.GT => -360, // UTC-6
            CountryCode.GU => 600, // UTC+10
            CountryCode.GW => 0, // UTC+0
            CountryCode.GY => -240, // UTC-4
            CountryCode.HK => 480, // UTC+8
            CountryCode.HM => 300, // UTC+5
            CountryCode.HN => -360, // UTC-6
            CountryCode.HR => 60, // UTC+1
            CountryCode.HT => -300, // UTC-5
            CountryCode.HU => 60, // UTC+1
            CountryCode.ID => 420, // UTC+7 (varies)
            CountryCode.IE => 0, // UTC+0
            CountryCode.IL => 120, // UTC+2
            CountryCode.IM => 0, // UTC+0
            CountryCode.IN => 330, // UTC+5:30
            CountryCode.IO => 360, // UTC+6
            CountryCode.IQ => 180, // UTC+3
            CountryCode.IR => 210, // UTC+3:30
            CountryCode.IS => 0, // UTC+0
            CountryCode.IT => 60, // UTC+1
            CountryCode.JE => 0, // UTC+0
            CountryCode.JM => -300, // UTC-5
            CountryCode.JO => 120, // UTC+2
            CountryCode.JP => 540, // UTC+9
            CountryCode.KE => 180, // UTC+3
            CountryCode.KG => 360, // UTC+6
            CountryCode.KH => 420, // UTC+7
            CountryCode.KI => 720, // UTC+12
            CountryCode.KM => 180, // UTC+3
            CountryCode.KN => -240, // UTC-4
            CountryCode.KP => 540, // UTC+9
            CountryCode.KR => 540, // UTC+9
            CountryCode.KW => 180, // UTC+3
            CountryCode.KY => -300, // UTC-5
            CountryCode.KZ => 360, // UTC+6 (varies)
            CountryCode.LA => 420, // UTC+7
            CountryCode.LB => 120, // UTC+2
            CountryCode.LC => -240, // UTC-4
            CountryCode.LI => 60, // UTC+1
            CountryCode.LK => 330, // UTC+5:30
            CountryCode.LR => 0, // UTC+0
            CountryCode.LS => 120, // UTC+2
            CountryCode.LT => 120, // UTC+2
            CountryCode.LU => 60, // UTC+1
            CountryCode.LV => 120, // UTC+2
            CountryCode.LY => 120, // UTC+2
            CountryCode.MA => 60, // UTC+1
            CountryCode.MC => 60, // UTC+1
            CountryCode.MD => 120, // UTC+2
            CountryCode.ME => 60, // UTC+1
            CountryCode.MF => -240, // UTC-4
            CountryCode.MG => 180, // UTC+3
            CountryCode.MH => 720, // UTC+12
            CountryCode.MK => 60, // UTC+1
            CountryCode.ML => 0, // UTC+0
            CountryCode.MM => 390, // UTC+6:30
            CountryCode.MN => 480, // UTC+8
            CountryCode.MO => 480, // UTC+8
            CountryCode.MP => 600, // UTC+10
            CountryCode.MQ => -240, // UTC-4
            CountryCode.MR => 0, // UTC+0
            CountryCode.MS => -240, // UTC-4
            CountryCode.MT => 60, // UTC+1
            CountryCode.MU => 240, // UTC+4
            CountryCode.MV => 300, // UTC+5
            CountryCode.MW => 120, // UTC+2
            CountryCode.MX => -360, // UTC-6 (varies)
            CountryCode.MY => 480, // UTC+8
            CountryCode.MZ => 120, // UTC+2
            CountryCode.NA => 120, // UTC+2
            CountryCode.NC => 660, // UTC+11
            CountryCode.NE => 60, // UTC+1
            CountryCode.NF => 690, // UTC+11:30
            CountryCode.NG => 60, // UTC+1
            CountryCode.NI => -360, // UTC-6
            CountryCode.NL => 60, // UTC+1
            CountryCode.NO => 60, // UTC+1
            CountryCode.NP => 345, // UTC+5:45
            CountryCode.NR => 720, // UTC+12
            CountryCode.NU => -660, // UTC-11
            CountryCode.NZ => 720, // UTC+12
            CountryCode.O1 => 0, // Other
            CountryCode.OM => 240, // UTC+4
            CountryCode.PA => -300, // UTC-5
            CountryCode.PE => -300, // UTC-5
            CountryCode.PF => -600, // UTC-10
            CountryCode.PG => 600, // UTC+10
            CountryCode.PH => 480, // UTC+8
            CountryCode.PK => 300, // UTC+5
            CountryCode.PL => 60, // UTC+1
            CountryCode.PM => -180, // UTC-3
            CountryCode.PN => -480, // UTC-8
            CountryCode.PR => -240, // UTC-4
            CountryCode.PS => 120, // UTC+2
            CountryCode.PT => 0, // UTC+0
            CountryCode.PW => 540, // UTC+9
            CountryCode.PY => -240, // UTC-4
            CountryCode.QA => 180, // UTC+3
            CountryCode.RE => 240, // UTC+4
            CountryCode.RO => 120, // UTC+2
            CountryCode.RS => 60, // UTC+1
            CountryCode.RU => 180, // UTC+3 (varies)
            CountryCode.RW => 120, // UTC+2
            CountryCode.SA => 180, // UTC+3
            CountryCode.SB => 660, // UTC+11
            CountryCode.SC => 240, // UTC+4
            CountryCode.SD => 120, // UTC+2
            CountryCode.SE => 60, // UTC+1
            CountryCode.SG => 480, // UTC+8
            CountryCode.SH => 0, // UTC+0
            CountryCode.SI => 60, // UTC+1
            CountryCode.SJ => 60, // UTC+1
            CountryCode.SK => 60, // UTC+1
            CountryCode.SL => 0, // UTC+0
            CountryCode.SM => 60, // UTC+1
            CountryCode.SN => 0, // UTC+0
            CountryCode.SO => 180, // UTC+3
            CountryCode.SR => -180, // UTC-3
            CountryCode.ST => 0, // UTC+0
            CountryCode.SV => -360, // UTC-6
            CountryCode.SX => -240, // UTC-4
            CountryCode.SY => 120, // UTC+2
            CountryCode.SZ => 120, // UTC+2
            CountryCode.TC => -240, // UTC-4
            CountryCode.TD => 60, // UTC+1
            CountryCode.TF => 300, // UTC+5
            CountryCode.TG => 0, // UTC+0
            CountryCode.TH => 420, // UTC+7
            CountryCode.TJ => 300, // UTC+5
            CountryCode.TK => 780, // UTC+13
            CountryCode.TL => 540, // UTC+9
            CountryCode.TM => 300, // UTC+5
            CountryCode.TN => 60, // UTC+1
            CountryCode.TO => 780, // UTC+13
            CountryCode.TR => 180, // UTC+3
            CountryCode.TT => -240, // UTC-4
            CountryCode.TV => 720, // UTC+12
            CountryCode.TW => 480, // UTC+8
            CountryCode.TZ => 180, // UTC+3
            CountryCode.UA => 120, // UTC+2
            CountryCode.UG => 180, // UTC+3
            CountryCode.UM => -600, // UTC-10
            CountryCode.US => -300, // UTC-5 (varies)
            CountryCode.UY => -180, // UTC-3
            CountryCode.UZ => 300, // UTC+5
            CountryCode.VA => 60, // UTC+1
            CountryCode.VC => -240, // UTC-4
            CountryCode.VE => -240, // UTC-4
            CountryCode.VG => -240, // UTC-4
            CountryCode.VI => -240, // UTC-4
            CountryCode.VN => 420, // UTC+7
            CountryCode.VU => 660, // UTC+11
            CountryCode.WF => 720, // UTC+12
            CountryCode.WS => 780, // UTC+13
            CountryCode.XK => 60, // UTC+1
            CountryCode.YE => 180, // UTC+3
            CountryCode.YT => 180, // UTC+3
            CountryCode.ZA => 120, // UTC+2
            CountryCode.ZM => 120, // UTC+2
            CountryCode.ZW => 120, // UTC+2
            _ => 0,
        };

        return new CountryInfo(timezoneOffset, displayName);
    }
}
