<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\osu.Plugin.LegacyBreakOverlay\osu.Plugin.LegacyBreakOverlay.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ppy.osu.Game" Version="2025.1209.0" />
  </ItemGroup>
</Project>
