using System.Collections;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using AccessItEasy;
using osu.Framework.Allocation;
using osu.Framework.Extensions.TypeExtensions;
using osu.Framework.Logging;

namespace osu.Game.Plugins;

/// <summary>
/// Provides a factory for creating AOP proxies for dependency activators, allowing plugins to hook into the dependency injection process of osu!framework and perform custom logic during activations.
/// </summary>
/// <remarks>
/// This serves as a non-intrusive AOP alternative to method hooking approaches like Harmony.
/// It's is a powerful tool allowing you listen on all activations of a specific type without enumerating hierarchy of drawables.
/// Especially useful when you want to modify the behaviour of all instances of a specific type, but you don't have control over their creation or you want to avoid maintaining a large number of activator hooks for different types in the hierarchy.
/// </remarks>
public static partial class DependencyActivatorProxyFactory
{
    private static readonly object proxyLock = new();
    private static readonly Dictionary<Type, IDependencyActivatorProxy> proxy_cache = new();

    /// <summary>
    /// Gets a proxy for the activator of the specified type, which allows hooking into the activator delegates and perform dependency caching and injection in a more flexible way.
    /// </summary>
    /// <param name="candidateType">The type of the dependency injection candidate</param>
    /// <returns>A hookable proxy for the activator of the specified type</returns>
    /// <remarks>
    /// Due to osu!framework's activator caching mechanism, the proxy instance may LOSE if there are multiple threads activating the same type of drawable at the same time, which may cause activator hooking to fail. 
    /// To avoid this, it's recommended to call this method in a module initializer, the plugin loader loads assembly at a quite early stage when there's no async loading on going.
    /// </remarks>
    public static IDependencyActivatorProxy GetProxy(Type candidateType)
    {
        lock (proxyLock)
        {
            if (!proxy_cache.TryGetValue(candidateType, out var proxy))
            {
                DependencyActivator activator;

                if (typeof(ISourceGeneratedDependencyActivator).IsAssignableFrom(candidateType))
                    activator = prepareSourceGeneratedActivator(candidateType);
                else
                    activator = DependencyActivator.getActivator(candidateType);

                proxy_cache[candidateType] = proxy = createProxy(activator);
            }

            return proxy;
        }
    }

    private static bool GetRegisterForDependencyActivationMethodInfo(Type candidateType, out MethodInfo? registerMethodInfo)
    {
        registerMethodInfo = candidateType.GetInterfaceMap(typeof(ISourceGeneratedDependencyActivator))
                                          .TargetMethods
                                          .FirstOrDefault(m => m.Name == nameof(ISourceGeneratedDependencyActivator.RegisterForDependencyActivation)
                                                            && m.GetParameters().Length == 1
                                                            && m.GetParameters()[0].ParameterType == typeof(IDependencyActivatorRegistry));

        return registerMethodInfo?.DeclaringType == candidateType;
    }

    private static unsafe DependencyActivator prepareSourceGeneratedActivator(Type candidateType)
    {
        if (GetRegisterForDependencyActivationMethodInfo(candidateType, out var registerMethodInfo))
        {
            Debug.Assert(registerMethodInfo is not null);

            RuntimeHelpers.PrepareMethod(registerMethodInfo.MethodHandle);

            Logger.Log($"Preparing source generated activator for {candidateType.FullName}, using method {registerMethodInfo.DeclaringType.ReadableName()}.{registerMethodInfo}.", level: LogLevel.Verbose);

            // Importantly, we must use the function pointer instead of calling it directly here:
            // We want to avoid calling into an overriden implementatoin of RegisterForDependencyActivation,
            // as it's not guaranteed that the implementor will call base.RegisterForDependencyActivation, which may cause the activator proxy to not be created and hooked correctly.
            // By using the function pointer, we can ensure that we're calling the original implementation of RegisterForDependencyActivation, which is generated by the source generator and contains the necessary logic to register the activator proxy.
            var pRegisterMethod = (delegate* managed<ISourceGeneratedDependencyActivator, IDependencyActivatorRegistry, void>)registerMethodInfo.MethodHandle.GetFunctionPointer();

            Debug.Assert(pRegisterMethod is not null);

            // All drawables are IDisposable, so if we called .ctor, we must also call Dispose as well, which may cause unwanted side effects.
            // Also, contructor may contains unwanted side effects, so we must avoid calling it.
            var instance = (ISourceGeneratedDependencyActivator)RuntimeHelpers.GetUninitializedObject(candidateType);

            pRegisterMethod(instance, DependencyActivator.activator_proxy);
        }

        return ensureSourceGeneratedActivatorInitialised(candidateType);
    }

    private static DependencyActivator ensureSourceGeneratedActivatorInitialised(Type candidateType)
    {
        if (DependencyActivator.activator_cache[candidateType] is not { } cachedActivator)
        {
            Logger.Log($"Source generated activator for {candidateType.FullName} didn't initialize activator cache, using reflection activator as fallback, performance may be affected.", level: LogLevel.Verbose);
            return DependencyActivator.getActivator(candidateType);
        }

        return new DependencyActivator(cachedActivator);
    }

    private static IDependencyActivatorProxy createProxy(DependencyActivator activator) => new ActivatorProxy(activator);

    /// <summary>
    /// Represents a wrapper of the original <see cref="osu.Framework.Allocation.DependencyActivator"/> instance, allowing access to its internal members and perform activator hooking.
    /// </summary>
    private readonly struct DependencyActivator
    {
        private readonly object activator;

        public DependencyActivator(object activator)
        {
            Debug.Assert(activator.GetType() == activatorType);

            this.activator = activator;
        }

        #region Equality members

        public static IDictionary activator_cache => get_activator_cache(null!);
        public static IDependencyActivatorRegistry activator_proxy => get_activator_proxy(null!);

        public List<InjectDependencyDelegate> injectionActivators => get_injectionActivators(activator);
        public List<CacheDependencyDelegate> buildCacheActivators => get_buildCacheActivators(activator);

        #endregion

        private static readonly Type activatorType = typeof(InjectDependencyDelegate).Assembly.GetType(TypeName, throwOnError: true)!;

        #region Accessors

        private const string TypeName = "osu.Framework.Allocation.DependencyActivator";

        [PrivateAccessor(PrivateAccessorKind.StaticField, Name = nameof(activator_cache))]
        private static extern IDictionary get_activator_cache([PrivateAccessorType(TypeName)] object typeRef);

        [PrivateAccessor(PrivateAccessorKind.StaticField, Name = nameof(activator_proxy))]
        private static extern IDependencyActivatorRegistry get_activator_proxy([PrivateAccessorType(TypeName)] object typeRef);

        [PrivateAccessor(PrivateAccessorKind.Field, Name = nameof(injectionActivators))]
        private static extern List<InjectDependencyDelegate> get_injectionActivators([PrivateAccessorType(TypeName)] object instance);

        [PrivateAccessor(PrivateAccessorKind.Field, Name = nameof(buildCacheActivators))]
        private static extern List<CacheDependencyDelegate> get_buildCacheActivators([PrivateAccessorType(TypeName)] object instance);

        [PrivateAccessor(PrivateAccessorKind.StaticMethod, Name = nameof(initialiseSourceGeneratedActivators))]
        private static extern void initialiseSourceGeneratedActivators([PrivateAccessorType(TypeName)] object typeRef, object candidate);

        [PrivateAccessor(PrivateAccessorKind.StaticMethod, Name = nameof(getActivator))]
        private static extern object getActivator([PrivateAccessorType(TypeName)] object typeRef, Type targetType);

        internal static void initialiseSourceGeneratedActivators(object obj) => initialiseSourceGeneratedActivators(null!, obj);

        internal static DependencyActivator getActivator(Type targetType) => new DependencyActivator(getActivator(null!, targetType));

        #endregion
    }

    /// <summary>
    /// A proxy class which hooks the original activator delegates and exposes events for external hooking. 
    /// The events are invoked before and after the original delegates to ensure the expected order of execution.
    /// </summary>
    private class ActivatorProxy : IDependencyActivatorProxy
    {
        internal readonly List<InjectDependencyDelegate> injectionActivators;
        internal readonly List<CacheDependencyDelegate> buildCacheActivators;

        public event CacheDependencyDelegate? OnCaching;
        public event CacheDependencyDelegate? OnCached;
        public event InjectDependencyDelegate? OnInjecting;
        public event InjectDependencyDelegate? OnInjected;

        public ActivatorProxy(DependencyActivator activator)
        {
            var originalInjectionActivatorsList = activator.injectionActivators;
            var originalBuildCacheActivatorsList = activator.buildCacheActivators;

            var injectionActivators = activator.injectionActivators.ToList();
            var buildCacheActivators = activator.buildCacheActivators.ToList();

            assertNotNested(injectionActivators);
            assertNotNested(buildCacheActivators);

            // framework's original activators
            this.injectionActivators = injectionActivators;
            this.buildCacheActivators = buildCacheActivators;

            originalBuildCacheActivatorsList.Clear();
            originalBuildCacheActivatorsList.Add(Cache);

            originalInjectionActivatorsList.Clear();
            originalInjectionActivatorsList.Add(Inject);
        }

        [Conditional("DEBUG")]
        private static void assertNotNested(IEnumerable<Delegate> activators)
        {
            foreach (var d in activators)
            {
                if (d.Target is IDependencyActivatorProxy)
                    throw new InvalidOperationException("Nested proxying detected, which may cause unexpected behaviour.");
            }
        }

        private IReadOnlyDependencyContainer Cache(object target, IReadOnlyDependencyContainer dependencies, CacheInfo info)
        {
            if (OnCaching is { } onCaching)
                dependencies = onCaching(target, dependencies, info);

            foreach (var cacheDelegate in buildCacheActivators)
                dependencies = cacheDelegate(target, dependencies, info);

            if (OnCached is { } onCached)
                dependencies = onCached(target, dependencies, info);

            return dependencies;
        }

        private void Inject(object target, IReadOnlyDependencyContainer dependencies)
        {
            OnInjecting?.Invoke(target, dependencies);

            foreach (var injectDelegate in injectionActivators)
                injectDelegate(target, dependencies);

            OnInjected?.Invoke(target, dependencies);
        }
    }
}

/// <summary>
/// A proxy interface allowing you listen on all drawable activations, and perform loading and caching of dependencies in the same way as normal activators.
/// </summary>
public partial interface IDependencyActivatorProxy
{
    /// <summary>
    /// Invoked before the original cache delegates. This method is the first to be invoked during the activator execution.
    /// </summary>
    event CacheDependencyDelegate? OnCaching;

    /// <summary>
    /// Invoked after the original cache delegates, but before the injection delegates.
    event CacheDependencyDelegate? OnCached;

    /// <summary>
    /// Invoked before the original injection delegates.
    /// </summary>
    event InjectDependencyDelegate? OnInjecting;

    /// <summary>
    /// Invoked after the original injection delegates. This method is the last to be invoked during the activator execution.
    /// </summary>
    event InjectDependencyDelegate? OnInjected;
}
