<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Beatmaps\**\*" />
    <EmbeddedResource Include="Fonts\**\*" />
    <EmbeddedResource Include="Samples\**\*" />
    <EmbeddedResource Include="Skins\**\*" />
    <EmbeddedResource Include="Shaders\**\*" />
    <EmbeddedResource Include="Textures\**\*" />
    <EmbeddedResource Include="Tracks\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\osu.Game.Plugins\osu.Game.Plugins.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\osu.Game.Plugins.Skins\osu.Game.Plugins.Skins.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.Fonts" Version="2.1.3" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
    <!-- osu!framework already depends on ImageSharp, so we don't want to copy this to the output directory. -->
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ppy.osu.Game" Version="2025.1209.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fody" Version="6.9.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="..\AccessItEasy\AccessItEasy\AccessItEasy.csproj">
      <!-- AccessItEasy only contains marker types, references were removed when weaving -->
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\AccessItEasy\AccessItEasy.Fody\AccessItEasy.Fody.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <OutputItemType>WeaverFiles</OutputItemType>
    </ProjectReference>
  </ItemGroup>

</Project>
