<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\osu.Game.Rulesets.PluginsLoader\osu.Game.Rulesets.PluginsLoader.csproj" />

    <!-- TODO: remove these, test only -->
    <ProjectReference Include="..\osu.Plugin.Template\osu.Plugin.Template.csproj" />
    <ProjectReference Include="..\osu.Plugin.MainMenuPlayer\osu.Plugin.MainMenuPlayer.csproj" />
    <ProjectReference Include="..\osu.Plugin.StableIntegration\osu.Plugin.StableIntegration.csproj" />
    <ProjectReference Include="..\osu.Plugin.LegacyExperience\osu.Plugin.LegacyExperience.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ppy.osu.Game" Version="2025.1209.0" />
    <!-- for test purpose, can be commented if unnecessary -->
    <PackageReference Include="ppy.osu.Game.Rulesets.Osu" Version="2025.1209.0" />
  </ItemGroup>

  <ItemGroup Label="Package References">
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
  </ItemGroup>
</Project>
