<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\osu.Plugin.LegacyLeaderboard\osu.Plugin.LegacyLeaderboard.csproj" />
    <ProjectReference Include="..\osu.Game.Plugins.Skins.Testing\osu.Game.Plugins.Skins.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ppy.osu.Game" Version="2025.1209.0" />
    <PackageReference Include="ppy.osu.Game.Rulesets.Osu" Version="2025.1209.0" />
  </ItemGroup>
</Project>
